
linux:
	g++ main.cpp ModelLoader/ModelLoader.cpp ModelLoader/PLYLoader.cpp ModelLoader/FormatDetector.cpp -I ./ -o app.out
windows:
	g++ main.cpp ModelLoader/ModelLoader.cpp ModelLoader/PLYLoader.cpp ModelLoader/FormatDetector.cpp -I ./ -o app.exe

clean:
	rm -rf app.out app.exe
