/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_glbasicframework_Native */

#ifndef _Included_com_example_glbasicframework_Native
#define _Included_com_example_glbasicframework_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_glbasicframework_Native
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_glbasicframework_Native_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_glbasicframework_Native
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_glbasicframework_Native_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_glbasicframework_Native
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_glbasicframework_Native_update
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
